services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: banking-sql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "!Password1"
      MSSQL_PID: "Developer"
    ports:
      - 1433:1433
    volumes:
      - banking_data:/var/opt/mssql

volumes:
  banking_data:
